services:
  bss:
    image: asaturovdg/bss:latest
    container_name: bss
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - bssnet
  db:
    image: postgres:15.2
    container_name: db
    ports:
      - "5430:5432"
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
    volumes:
      - ./sqls/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - bssnet
    restart: unless-stopped
networks:
  bssnet:
    driver: bridge